version: '3.8'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:latest
    container_name: postgres-bookstore
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d # Mount the scripts directory
    networks:
      - bookstore-network

  # BookStore Web API service
  bookstore-api:
    image: bookstore-web-api:latest
    container_name: bookstore-api
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=BookStore;Username=postgres;Password=123456"
    ports:
      - "3000:80"
    depends_on:
      - postgres
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge